- set_fact: my_ip={{ hostvars[inventory_hostname]['ansible_' + ethernet_interface]['ipv4']['address'] }}

- name: Install docker compose
  get_url:
     url: https://github.com/docker/compose/releases/download/1.7.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
     dest: /usr/local/bin/docker-compose
     mode: 0755
  when: ('arm' != '{{ ansible_architecture[0:3] }}')

- name: Update docker startup dependency for network
  replace:
    dest: /lib/systemd/system/docker.service
    regexp: (^After=)(network.target.*)
    replace: \1network-online.target \2

- name: Update docker startup requirement for network
  replace:
    dest: /lib/systemd/system/docker.service
    regexp: (^Requires=)(docker.socket.*)
    replace: \1network-online.target \2

- name: Update docker retry on failure
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^Restart=on-failure$
    insertafter: ^ExecStart.*
    line: Restart=on-failure

- name: Update docker retry on failure sleep time
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^RestartSec=5s$
    insertafter: ^Restart=on-failu.*
    line: RestartSec=5s

- name: reload systemd
  command: systemctl daemon-reload

- name: restart docker
  service: name=docker state=restarted

