# create dynamic groups
- hosts: wallaroo-follower*
  tasks:
  - name: Create a group of all followers for wallaroo
    group_by: key=wallaroo-followers

- hosts: wallaroo-leader*
  vars:
    ethernet_interface: enp0s8
  tasks:
  - name: Create a group of all leaders for wallaroo
    group_by: key=wallaroo-leaders
  - name: Set IPs for ptpd unicast
    set_fact: ptpd_destinations="{% if groups['wallaroo-followers'] is defined %}{% for host in groups['wallaroo-followers'] %}{{ hostvars[host]['ansible_' + ethernet_interface]['ipv4']['address'] }}{% if not loop.last %},{% endif %}{% endfor %}{% else %}127.0.0.1{% endif %}"

- hosts: wallaroo-leaders:wallaroo-followers
  tasks:
  - name: Create a group of all hosts for wallaroo
    group_by: key=wallaroo-all

# Apply common configuration to all hosts
- hosts: wallaroo-all
  roles:
  - { role: common, become: yes }

# Configure and deploy leader servers.
- hosts: wallaroo-leaders
  vars:
    ethernet_interface: enp0s8
    ptpd_role: master
    ptpd_transport: unicast
    swarm_image: swarm
    consul_image: gliderlabs/consul
    docker_users: [ vagrant, wallaroo ]
    userland_proxy: true
    docker_dockerpy_version: "1.9.0"
  roles:
  - { role: ptpd, become: yes }
  - { role: docker, become: yes }

# Configure and deploy follower servers.
- hosts: wallaroo-followers
  vars:
    ethernet_interface: enp0s8
    ptpd_role: slave
    ptpd_transport: unicast
    leader_ip: "{{ hostvars[groups['wallaroo-leaders'][0]]['ansible_' + ethernet_interface]['ipv4']['address'] }}"
    swarm_image: swarm
    consul_image: gliderlabs/consul
    docker_users: [ vagrant, wallaroo ]
    userland_proxy: true
    docker_dockerpy_version: "1.9.0"
  roles:
  - { role: ptpd, become: yes }
  - { role: docker, become: yes }

